### ISSUE TITLE
CW 2.4.5:  Trap illegal xsl characters in customer submitted text

### ISSUE THREAD

**Issue by DavidB-ESDM** [exeGesIS-SDM/CAMS-Web#309]
CAMS Desktop error when processing Issue1  submissions.  Problem field containing an ampersand fails to process.  Job here is to trap and remove any text the XSLTs may have a problem processing.  Possible characters are:  "   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;

Sorry Git Hub is escaping them  will attach a screenshot.
D
![Capture](https://user-images.githubusercontent.com/35491502/105882700-df246100-5ffd-11eb-9e83-3aaa2ab54380.PNG)

**Comment by joerichardsESDM** [comment]
Implemented this.

**Comment by richardcesdm** [comment]
I have tested this in the current staging/dev and when writing 

test & illegal character

it produces this: 

![image](https://user-images.githubusercontent.com/24268198/109498274-27b2bc80-7a8b-11eb-9ad9-029760114042.png)

**Comment by richardcesdm** [comment]
Hello, I've had some more experience with this now and it definitely needs a bit more work as it isn't really practical for release at the moment.

Here is an example string I have submitted as a problem description: 

_testing characters here is a & character and here is a ' character lot's (and) lot's & lot's "test" do we allow all types ; ?_ 

In my CAMS Web 2.3 reference copy this is how the string is looking: 

_testing characters here is a &amp; character and here is a ' character lot's (and) lot's &amp; lot's "test" do we allow all types ; ?_ 

So it didn't handle the & character but the others were OK.

However here is the same string in the current CAMS Web 2.4.5: 

_testing characters here is a &amp;amp; character and here is a &amp;apos; character lot&amp;apos;s (and) lot&amp;apos;s &amp;amp; lot&amp;apos;s &amp;quot;test&amp;quot; do we allow all types ; ?_ 

So it now seems unhappy about a wider variety of characters than it did before.

**Comment by richardcesdm** [comment]
I have done some more extensive testing around illegal characters

in the current version of 2.4.5 I believe the recent change has now been rolled back, this is the original string: 

`testing characters here is a & character and here is a ' character lot's (and) lot's & lot's "test" do we allow all types ; ?`

This is how it appears in the xml after submit:

`testing characters here is a &amp; character and here is a ' character lot's (and) lot's &amp; lot's \"test\" do we allow all types ; ?`

So within this string, it is only the & characters not being handled, but these do not prevent the issue from being processed. 

**However I have noted that if a = character (equals sign) is submitted within the text at any point this will cause the record submission to fail.** I think we either need to allow this character or provide a more meaningful message as at the moment the website just dumps the potential submission which would be frustrating for any users that have written a long description.

I will continue doing more testing to determine the limits of illegal characters in CAMS Web when I get time.

**Comment by joerichardsESDM** [comment]
I've fixed the problem of an = sign in the text breaking the JSON - that was actually a separate issue than the XML problems detailed above

**Comment by richardcesdm** [comment]
confirming this is still a problem with 2.4.6 (I thought it had been fixed but was mistaken) when submitting the following string:
